### ISSUE TITLE
Open Issues reported for version 3.3.2 in Redmine that were not fixed in version 3.3.3

### ISSUE THREAD

**Issue by enov** [kohana/core#576]
- [x] [4836](http://dev.kohanaframework.org/issues/4836) Add case `jpe` for switch in function _save_function() on `modules\image\classes\Kohana\Image\GD.php`, let's match `config/mimes.php` array map
- [x] [4835](http://dev.kohanaframework.org/issues/4835) My ORM
- [x] [4833](http://dev.kohanaframework.org/issues/4833) Problem with folder structure?
- [x] [4806](http://dev.kohanaframework.org/issues/4806) Invalid query with "":"" as alias in SQLite DB"
- [x] [4797](http://dev.kohanaframework.org/issues/4797) Userguide,.htaccess

**Comment by enov** [comment]
[4835](http://dev.kohanaframework.org/issues/4835) and [4833](http://dev.kohanaframework.org/issues/4833) are invalid.

**Comment by enov** [comment]
[4836](http://dev.kohanaframework.org/issues/4836): added `jpe` file extension as IMAGETYPE_JPEG in kohana/image@c8d7dc42f751d4ce4819292c09cbf16dcc7a6004

**Comment by enov** [comment]
[4806](http://dev.kohanaframework.org/issues/4806) might also be invalid. PDO uses no identifiers, it can be set by creating a new driver that extends PDO.

**Comment by enov** [comment]
[4797](http://dev.kohanaframework.org/issues/4797) seems to me a request to add some undocumented installation glitches, related to Apache .htaccess, to the manual. There is a suggestion by @WinterSilence to enhance the RewriteRule, that might be worth looking at. However, I did not note anything pressing.

**Comment by enov** [comment]
@acoulton I believe all these open issues should be closed in Redmine.

**Comment by enov** [comment]
Can we say it's time to release? :surfer:

**Comment by enov** [comment]
Is there a hope for a release?

**Comment by acoulton** [comment]
@enov sorry, I somehow didn't see your last post.

I say let's go for it, there's a lot of good changes come through.

Who's going to do it? You/me/@shadowhand?

**Comment by enov** [comment]
I guess @shadowhand should be around, in case something wrong happens, either you or me, it does not matter.

**Comment by enov** [comment]
Do you think we should delete 56e452c53b95c2d5d5ebe0c9d5ad0feb9646fa30 (git reset --hard)?

**Comment by enov** [comment]
so that we won't face a merge conflict once we create a release branch to change the codename and release version number.

**Comment by enov** [comment]
@acoulton I have started to locally merge `develop` braches of the modules to `master` right now, with a `3.3/release/3.3.3` branches in between.

I think it is easier to tag them after pushing, through Github interface.

Am I missing something?

**Comment by acoulton** [comment]
Yeah, I guess that will work. Presume you've updated the version number in kohana/core?

I wouldn't delete 56e452c as that commit reference will be in people's `composer.lock` and their `composer install` will suddenly start failing - which wouldn't make you popular!

I'd probably merge `3.3/master` back into `3.3/develop` and then start the release branch after that, then there's no merge conflict.

**Comment by enov** [comment]
I am done with the modules, I guess. I also pushed codebench module. Could you look if it is OK?

**Comment by acoulton** [comment]
@enov I need to head off, but seems like the merge to master in kohana/cache went wrong, the travis configuration is broken and badges have gone missing from the README.

**Comment by enov** [comment]
I was able to reset that. I will see how I can try again. I guess it happened because of a merge/revert directly in master.

**Comment by enov** [comment]
The only solution to this, as far as I can see, is to merge `3.3/master` into `3.3/develop` and replay the commits for kohana/cache#56?

**Comment by enov** [comment]
This seems to be helpful:
https://metlos.wordpress.com/2012/01/13/git-merging-after-a-revert/

**Comment by enov** [comment]
Released.

**Comment by acoulton** [comment]
@enov nice one, it looks like maybe you never pushed your unittest repo as the kohana/kohana build is broken - commit ref is not found.

**Comment by acoulton** [comment]
And also, the 3.3/master branches then all need to be merged back to 3.3/develop and also 3.4/develop

**Comment by rjd22** [comment]
This is for you guys: :tada: @acoulton @enov

**Comment by enov** [comment]
Thanks @rjd22.

> you never pushed your unittest repo as the kohana/kohana build is broken - commit ref is not found.

You're right @acoulton :+1:  It's done now.

**Comment by acoulton** [comment]
@enov ![thanks and well done!](http://stream1.gifsoup.com/view2/2190014/slowmotion-champagne-opening-o.gif)

**Comment by enov** [comment]
Haha! Thanks to you too, @acoulton, it would not have happened without you.

**Comment by enov** [comment]
> And also, the 3.3/master branches then all need to be merged back to 3.3/develop and also 3.4/develop

Will take care of that, too.

**Comment by rakucmr** [comment]
Great job, thank you for all your efforts!
When will you publish also on Kohana website?

**Comment by enov** [comment]
Thanks @raku! I just made a PR to the website https://github.com/kohana/kohanaframework.org/pull/20.
Cheers!

**Comment by rakucmr** [comment]
@enov I want to rewrite Auth module to include new features like, login throttling, hash using password_compat, driver for using oauth and open id, password reset, user activation, should I make It compatible with current Auth version or start it from beginning?
What other features do you think it should contain?

**Comment by enov** [comment]
All those features you stated are important, but I am not entitled to take the decision and/or give you the green light. You need to open a new issue at https://github.com/kohana/auth and discuss things there. Also, it seems there is consensus to drop the auth module altogether in the future, because it seems it is a maintenance burden.

**Comment by rakucmr** [comment]
I've opened but was closed by the owner of the Kohana Framework :)
If we drop this, then ORM, then others modules, what will remain from this framework ... I think the idea of a framework is to offer more and more features, not to drop them.
If something is not good repair it until is good enough not just drop it.

**Comment by rjd22** [comment]
@raku the goal is a minimum framework that handles requests and responses and use external libraries to solve issues other than that. Auth is a easy problem to solve but can also be a really hard one depending on what the requirements are. The PHP world is evolving and using external libraries is a breeze not thanks to composer.

Our reasons for dropping it is that there are others solving the problem way better than we ever would be able to do. Like https://github.com/cartalyst/sentry for solving normal auth, https://github.com/thephpleague for oauth and https://github.com/doctrine/doctrine2 for ORM. We could never solve all those problems better than they do now with the amount of people we have working on Kohana right now.

So it would be better to solve the problems we can like request and response and everything that is connected to that.

**Comment by rakucmr** [comment]
:) Here is the problem that you think it like a small framework.
I think you will find other solutions that makes things better than Kohana if you split it component by component. The power of a framework is in all of it's components together.

**Comment by acoulton** [comment]
@raku a small framework means you're not tied to complex "catch-all" implementations, but can pick the right libraries for the right jobs. It also means you get the benefit of a much larger development team (each specialising in and working on the component they produce) rather than having to rely on a small group of people to implement the whole of Kohana.

If you think there's a need for a modern Kohana auth module you're of course welcome to write one and publish it - but I don't think you'll find any of the core team keen to work with you on making it an "official" kohana module. We're all fairly clear that this is a solved problem, and the only reason to keep kohana/auth dragging along is for legacy compatibility.

If a developer is going to have to learn and integrate with a new API anyway, they'd be better off choosing one of the third party solutions that already exist and work very well.
